class SetCategories:
    def set_cat(self):
        print('[+] Navigate to the sites below and submit your categorization request.')
        print('[*] Hint: Use Finance or Health to get past categorization checking.')
        print('[+] BlueCoat: ')
        print('[*]         https://sitereview.bluecoat.com/#/')
        print('')
        print('[+] Fortiguard: ')
        print('[*]         https://fortiguard.com/faq/wfratingsubmit')
        print('')
        print('[+] IBM xForce: ')
        print('[*]         https://exchange.xforce.ibmcloud.com/url/<domain name>')
        print('')
        print('[+] McAfee TrustedForce: ')
        print('[*]         https://www.trustedsource.org/')
        print('[*]         Check Category for domain then submit change.')
        print('')
        print('[+] WebSense: ')
        print('[*]         https://csi.forcepoint.com/')
        print('[*]         Check Category for domain then click "Suggest a different classification".')
        print('')
        